// Local Pittsburgh fixtures. Shape intentionally mirrors the Toronto feed so
// the production data adapter can be swapped in without changing the UI.
window.SYNTHETIC_ROAD_EVENTS = [
  { id: "pgh-1", latitude: 40.4406, longitude: -79.9959, road: "Liberty Avenue", name: "Downtown construction", type: "CONSTRUCTION", currImpact: "Medium", maxImpact: "High", roadClass: "Major Arterial", directionsAffected: "BOTH_DIRECTIONS", specialEvent: "No", description: "Lane reduction near downtown.", startTime: Date.now() - 86400000, endTime: Date.now() + 86400000 * 8 },
  { id: "pgh-2", latitude: 40.4467, longitude: -80.0025, road: "Penn Avenue", name: "Festival traffic", type: "ROAD_CLOSED", currImpact: "High", maxImpact: "High", roadClass: "Major Arterial", directionsAffected: "BOTH_DIRECTIONS", specialEvent: "Yes", description: "Synthetic event closure for testing.", startTime: Date.now() - 3600000, endTime: Date.now() + 86400000 },
  { id: "pgh-3", latitude: 40.4381, longitude: -79.9502, road: "Forbes Avenue", name: "Utility work", type: "CONSTRUCTION", currImpact: "Low", maxImpact: "Medium", roadClass: "Minor Arterial", directionsAffected: "ONE_DIRECTION", specialEvent: "No", description: "One lane affected near Oakland.", startTime: Date.now() - 86400000 * 2, endTime: Date.now() + 86400000 * 5 },
  { id: "pgh-4", latitude: 40.4531, longitude: -80.0164, road: "West End Bridge", name: "Collision hazard", type: "HAZARD", currImpact: "High", maxImpact: "High", roadClass: "Major Arterial", directionsAffected: "ONE_DIRECTION", specialEvent: "No", description: "Synthetic crash hazard.", startTime: Date.now() - 7200000, endTime: Date.now() + 21600000 },
  { id: "pgh-5", latitude: 40.4262, longitude: -79.9788, road: "Birmingham Bridge", name: "Bridge maintenance", type: "ROAD_CLOSED", currImpact: "Medium", maxImpact: "High", roadClass: "Minor Arterial", directionsAffected: "BOTH_DIRECTIONS", specialEvent: "No", description: "Temporary bridge restriction.", startTime: Date.now() - 86400000, endTime: Date.now() + 86400000 * 3 },
  { id: "pgh-6", latitude: 40.4612, longitude: -79.9931, road: "East Ohio Street", name: "Scheduled work", type: "CONSTRUCTION", currImpact: "None", maxImpact: "Low", roadClass: "Minor Arterial", directionsAffected: "ONE_DIRECTION", specialEvent: "No", description: "Synthetic low-impact event.", startTime: Date.now() + 86400000, endTime: Date.now() + 86400000 * 4 }
];
